---
title: "BILGER-HANS-HOMEWORK-01"
author: "Hans Bilger"
date: "February 5, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gettysburg address
```{r}
library(stringr)
abe <- ("Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.")

# 1 word character strings
abe_split <- c(str_split(abe, " ", simplify = TRUE))

# every third element
abe3 <- abe_split[seq(from = 1, to = 30, by = 3)]

##remove punctuation and special characters
breathless <- gsub("[[:punct:]]","", abe)

#1 word character strings, no punctuation
breathless_split <- c(str_split(breathless, " ", simplify = TRUE))

#every third element, no punctuation
breathless3 <- breathless_split[seq(from = 1, to = 30, by = 3)]

```

##Matricies
```{r}

m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
m

#Given the matrix, m, above, extract the 2nd, 3rd, and 6th columns and assign them to the variable x
x <- m[, c(2,3,6)]
x

#Given the matrix, m, above, extract the 6th to 8th row and assign them to the variable x
x <- m[c(6:8), ]
x

#Given the matrix, m, above, extract the elements from row 2, column 2 to row 6, column 9 and assign them to the variable x

x <- m[2:6, 2:9]
x

#Construct a 4-dimensional, 400 element array (5 x 5 x 4 x 4) named a consisting of the numbers 400 to 1 (i.e., a descending series)

a <- array(data = 400:1, dim = c(5, 5, 4, 4))
a

#Given this matrix, what would the following return?

#a[1, 1, 1, 2]
##275

#a[2, 3, 2, ]
##364 264 164  64

#a[1:5, 1:5, 3, 3]
#     [,1] [,2] [,3] [,4] [,5]
#[1,]  150  145  140  135  130
#[2,]  149  144  139  134  129
#[3,]  148  143  138  133  128
#[4,]  147  142  137  132  127
#[5,]  146  141  136  131  126

```

##Primate Taxonomy
######*Below is the code I came up with when I did this on my own. Below that is the solution that came out of working with Allison and Caitlin.*
```{r}

Platyrrhini <- list("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini <- list("Cercopithecidae", "Hylobatidae", "Hominidae")
Tarsioidea <- list("Tarsiidae")
Anthropoidea <- list(Platyrrhini, Catarrhini)
Haplorhini <- list(Anthropoidea, Tarsioidea)
Lorisoidea <- list("Lorisidae", "Galagidae")
Lemuroidea <- list("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")
Strepsirhini <- list(Lorisoidea, Lemuroidea)
Primates <- list(Strepsirhini, Haplorhini)


names(Primates) <- c("Strepsirhini", "Haplorhini")
names(Anthropoidea) <- c("Platyrrhini", "Catarrhini")
names(Haplorhini) <- c("Anthropoidea", "Tarsioidea")
names(Strepsirhini) <- c("Lorisoidea", "Lemuroidea")

Primates
Anthropoidea
Haplorhini
Platyrrhini
```

######*Allison/Caitlin primate solution*
```{r}

Platyrrhini <- c("Cebidae", "Atelidae", "Pitheciidae")

Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")

Anthropoidae <- matrix(data=(rbind(Platyrrhini, Catarrhini)), nrow=2, ncol=3, byrow=FALSE)
rownames(Anthropoidae) <- c("Platyrrhini", "Catarrhini")

Anthropoidae

Tarsioidae <- c("Tarsiidae")

Haplorhini <- list(Anthropoidae, Tarsioidae)
names(Haplorhini) <- c("Anthropoidae", "Tarsioidae")

Haplorhini

Lorisoidae <- c("Lorisidae", "Galagidae")

Lemuroidae <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")

Strepsirhini <- list(Lorisoidae, Lemuroidae)
names(Strepsirhini) <- c("Lorisoidae", "Lemuroidae")

Strepsirhini

Primates <- list(Haplorhini, Strepsirhini)
names(Primates) <- c("Haplorhini", "Strepsirhini")

Primates
```

#Matricies again
```{r}
#Store the following numbers as a 5 x 3 matrix: 3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2. Be sure to fill the matrix ROWWISE.

m <- matrix(data = c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2), nrow = 5, ncol = 3, byrow = TRUE)
View(m)

#Coerce the matrix to a data frame.
m <- as.data.frame(m)
View(m)
class(m)

#As a data frame, coerce the second column to be logical-valued (Boolean)
m[, 2] <- as.logical(m[, 2])
View(m)

#As a data frame, coerce the third column to be factor-valued
m[, 3] <- as.factor(m[, 3])
View(m)

#When you are done, use the str() command to show the data type for each variable in your dataframe.
str(m)

```

